### ISSUE TITLE
ERROR : ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by sapisuper** [OmniDB/OmniDB#1066]
Hi ,

I just get massive error log:

> [11/22/2019 09:27:37] ERROR [cherrypy.error:216] [22/Nov/2019:09:27:37] ENGINE Error in HTTPServer.tick
> Traceback (most recent call last):
>   File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cheroot/server.py", line 1770, in serve
>     self.tick()
>   File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cheroot/server.py", line 1993, in tick
>     conn = self.connections.get_conn(self.socket)
>   File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cheroot/connections.py", line 142, in get_conn
>     rlist, _, _ = select.select(list(socket_dict), [], [], 0.1)
> ValueError: filedescriptor out of range in select()

after that I can't access omnidb (**omnidb down**) . I just restart omnidb-server and service back to normal again.

my omnidb version is v2.16.0 build from source. running on Ubuntu 16.04.5 LTS. please check this issue? 

Thank you,

Satria

**Comment by sapisuper** [comment]
I just add reload script, it can be temporary solution for this issue. thanks
