### ISSUE TITLE
websocket_status_online is blue, websocket error

### ISSUE THREAD

**Issue by bbotte** [OmniDB/OmniDB#1130]
when multiple people open multiple TAB cases，i met a troubles, version is 2.15.0,   websocket_status_online is blue,

[05/05/2020 06:28:13] ERROR [OmniDB_app.QueryServer:596] *** Exception ***
Traceback (most recent call last):
File "OmniDB/ws_core.py", line 593, in on_message
File "threading.py", line 846, in start
RuntimeError: can't start new thread
ERROR:tornado.application:Uncaught exception GET /ws (192.168.0.243)
HTTPServerRequest(protocol='http', host='192.168.0.151:25482', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='192.168.0.243')
Traceback (most recent call last):
File "OmniDB/ws_core.py", line 593, in on_message
File "threading.py", line 846, in start
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "site-packages/tornado/websocket.py", line 649, in _run_callback
File "OmniDB/ws_core.py", line 597, in on_message
NameError: name 'v_response' is not defined
[05/05/2020 06:28:13] ERROR [OmniDB_app.QueryServer:653] *** Exception ***
Traceback (most recent call last):
File "OmniDB/ws_core.py", line 651, in send_response_thread_safe
File "site-packages/tornado/websocket.py", line 339, in write_message
tornado.websocket.WebSocketClosedError
[05/05/2020 06:28:13] ERROR [OmniDB_app.QueryServer:653] *** Exception ***
Traceback (most recent call last):
File "OmniDB/ws_core.py", line 651, in send_response_thread_safe
File "site-packages/tornado/websocket.py", line 339, in write_message
tornado.websocket.WebSocketClosedError
ERROR:tornado.application:Uncaught exception GET /ws (192.168.0.243)

restart service is ok

**Comment by felipebiox** [comment]
Hello bbotte,

Thank you for your report, there were quite a few issues with websocket in OmniDB.

**OmniDB 3 is now live** and the **websocket technology has been replaced**.

Connectivity issues and errors related to websocket are no longer affecting users.

I'm now closing this issue.

Best regards
