### ISSUE TITLE
OmniDB Windows Client detect as Virus by Windows Defender

### ISSUE THREAD

**Issue by dark0ni** [OmniDB/OmniDB#1185]
When i download 

https://omnidb.org/#downloads

OmniDB App v.3.0.2.b (Windows)
--
Platform Windows
Version omnidb_3.0.2b_windows.exe
md5 abc2ea7a4a4cab8e431529cb9d37dc0e

the browser blocks the download, and after installing Windows Defender detects a trojaner: Trojan:Win32/Wacatac.D9!ml

**Comment by felipebiox** [comment]
"Hi @dark0ni ,

Thank you for reporting this occurrence.

The short answer is that this is almost certainly a [false-positive related to pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/4633), as it has already been analysed by the developers. But we take security very seriously and I feel that this issue should receive a detailed summary on the topic, apologies in advance if I'm being redundant.

The first topic I'm mentioning here is the aspect of `false-positives` on Python builds.
This is a fairly common issue and not exclusive to OmniDB. Also, it would not be the first time we receive `false-positives`, as it occurred on previous versions of OmniDB with AV software too.

First of all, you should bear in mind that we use pyinstaller to build OmniDB, and our builds are compiled, packaged and tested on new and clean VMs/containers everytime we build a new version.

Still on the subject of `false-positives`, one thing to point is that pyinstaller is a very popular python module. Due to it's versatility, it's also often used by hackers to build malicious software, and in consequence, some security tools flag installing processes managed by pyinstaller as an attempt to compromise the system. This would be an example of a `false-positive`.

In any case, I will run another set of tests on different versions of Windows 10 and Defender today and get back to this issue.

Best regards"

**Comment by dark0ni** [comment]
For debugging help:

Windows 10, Version 2004
Windows Defender Version of Securityinformation: 1.327.241.0

**Comment by sisinio** [comment]
Hi,
I have the same problem with the same Win 10 version. 
At second run OmniDB wont' start because Windows Defender detects a trojaner: Trojan:Win32/Wacatac.D9!ml

![image](https://user-images.githubusercontent.com/5585987/98545017-1b64e280-2295-11eb-82b2-ad68c442d6e1.png)

https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Wacatac.D9!ml&threatid=2147757788

Best regards

**Comment by hardyansein** [comment]
By Symantec : 

Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: Heur.AdvML.B
File: C:\OmniDB\omnidb-server\omnidb-server.exe
Location: Deleted or access blocked

**Comment by felipebiox** [comment]
Hello folks,

Providing an update to this issue.
We did a second round of research and verified `false-positives`, all related to pyinstaller.
We are currently working on a solution.

Best regards

**Comment by MichaelDBA** [comment]
I created the latest issue related to this that you closed, #1201. You say these are "false-positives".  But how does that explain how my Virus checker, McAfee,  came up with a specific virus name, "**Suspect!5c9c7bf8fff5**"?

**Comment by MichaelDBA** [comment]
Any update on when the "fix" will be in?

**Comment by rafaelthca** [comment]
hi @MichaelDBA,

As my colleague @felipebiox explained, the reason why multiple antiviruses reported the same name is because OmniDB shares the same bootloader used in that particular virus, which I know nothing about but was probably bundled using the same technology.

I am already working on a fix to compile PyInstaller's bootloader myself to avoid these messages. Should be out in the next release.

**Comment by MichaelDBA** [comment]
Thank you for the explanation.  I guess I will stop using OmniDB until the next release comes out.

**Comment by felipebiox** [comment]
Hello folks,

We've been working on a fix for the `false-positives` generated over the use of pyinstaller.

Now we have builds available for the pre-release of 3.0.3b, which include this priority fix, but they are **NOT the final versions**, they are an improvement that reduce chances of being miss-interpreted. We tested them on quite a few versions of OS and security tools.

Those available and willing to help us test the new builds can find them available [here](https://drive.google.com/file/d/1xbcM5qM_XDgscRaIkh7UOAkwztH9KF5H/view).

Additional testing would be most appreciated.

Kind regards

**Comment by MichaelDBA** [comment]
Tried the new build, and for me, it got past the McAfee virus detector.  It brings up the usual Windows warning as follows:
```
Windows protected your PC

Microsoft Defender SmartScreen prevented an unrecognized app from starting.  Running this app might put your PC at risk.

App:  omnidb_3.0.3b-windows.exe
Publisher: | 2nd quadrant ltd

```
But when I proceeded with the install, got a bunch of errors:

```
Starting OmniDB...
Copying config file to home directory.
Running database migrations...
Operations to perform:
Apply all migrations: OmniDB_app, admin, auth, contenttypes, sessions, social_django
Running migrations:
Applying contenttypes.0001_initial... OK
Applying auth.0001_initial... OK
Applying OmniDB_app.0001_3_0_0... OK
Applying OmniDB_app.0002_3_0_1... OK
Applying OmniDB_app.0003_3_1_0... OK
Applying admin.0001_initial... OK
Applying admin.0002_logentry_remove_auto_add... OK
Applying admin.0003_logentry_add_action_flag_choices... OK
Applying contenttypes.0002_remove_content_type_name... OK
Applying auth.0002_alter_permission_name_max_length... OK
Applying auth.0003_alter_user_email_max_length... OK
Applying auth.0004_alter_user_username_opts... OK
Applying auth.0005_alter_user_last_login_null... OK
Applying auth.0006_require_contenttypes_0002... OK
Applying auth.0007_alter_validators_add_error_messages... OK
Applying auth.0008_alter_user_username_max_length... OK
Applying auth.0009_alter_user_last_name_max_length... OK
Applying auth.0010_alter_group_name_max_length... OK
Applying auth.0011_update_proxy_permissions... OK
Applying sessions.0001_initial... OK
Applying social_django.0001_initial... OK
Applying social_django.0002_add_related_name... OK
Applying social_django.0003_alter_email_max_length... OK
Applying social_django.0004_auto_20160423_0400... OK
Applying social_django.0005_auto_20160727_2333... OK
Applying social_django.0006_partial... OK
Applying social_django.0007_code_timestamp... OK
Applying social_django.0008_partial_timestamp... OK
Applying social_django.0009_auto_20191118_0520... OK
Applying social_django.0010_uid_db_index... OK
Attempting to migrate users, connections and monitoring units and snippets from OmniDB 2 to 3...
Creating user 'admin'...
User 'admin' already exists.
User 'admin' does not contain connections in the source database.
Attempting to create snippets of user 'admin'...
Attempting to create monitoring units of user 'admin'...
Database migration finished.
Starting OmniDB server...
Checking port availability...
Starting server OmniDB 3.0.3b at 127.0.0.1:8000.
[12/16/2020 07:46:31] ERROR [cherrypy.error:216] [16/Dec/2020:07:46:31] ENGINE Error in 'start' listener > Traceback (most recent call last): File "cherrypy\process\wspbus.py", line 230, in publish File "cherrypy\_cpserver.py", line 180, in start File "cherrypy\process\servers.py", line 184, in start File "cherrypy\process\servers.py", line 260, in wait File "portend.py", line 150, in occupied portend.Timeout: Port 8000 not bound on 127.0.0.1.
[12/16/2020 07:46:31] ERROR [cherrypy.error:216] [16/Dec/2020:07:46:31] ENGINE Shutting down due to error in start listener: Traceback (most recent call last): File "cherrypy\process\wspbus.py", line 268, in start File "cherrypy\process\wspbus.py", line 248, in publish cherrypy.process.wspbus.ChannelFailures: Timeout('Port 8000 not bound on 127.0.0.1.')

```

**Comment by rafaelthca** [comment]
hi @MichaelDBA,

Does this happen every time you restart OmniDB? Do you have something else in your machine running on port 8000? I don't expect that is the case as OmniDB checks port availability before actually starting the server.

If that is reproducible, can you try running OmniDB with admin rights to see if we get past that error?

Thanks.

Rafael.

**Comment by MichaelDBA** [comment]
It happened just the first time.  It didn't happen for subsequent starts of the app or server.

**Comment by dark0ni** [comment]
Microsoft Edge Browser has still a warning and the system too, but can now installed without being destroyed by the Windows Defender with version 3.0.3b
