### ISSUE TITLE
Credentials gets changed during reboot

### ISSUE THREAD

**Issue by BarryThrill** [OmniDB/OmniDB#1221]
Hey guys!

Im proper new to OmniDB where I followed few guides to install OmniDB with Debian 10.

Yesterday I managed to get it all work where I changed my port only to 2082 and then was able to access through ip:port on browser. I was able to login as `admin admin` and then I changed the superuser username and password to `hello world1`.

After a night and a reboot of the server. It automatic started the omnidb through `systemctl ` and I was able to access through ip:port through browser again. However it seems like I am not able to login anymore and even if I type `admin admin or hello world1` it says its invalid and seems like it has automatically changed it and I do not know what I can do from here and what the reason why it does it as well. It seems like I had the issue as well yesterday.

Im not sure what more I can post for information but please, if anything is missing. Let me know!

```
root@testServer:~# omnidb-server -u hello worl1
Running database migrations...
Operations to perform:
  Apply all migrations: OmniDB_app, admin, auth, contenttypes, sessions, social_django
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "django/db/backends/utils.py", line 84, in _execute
  File "django/db/backends/sqlite3/base.py", line 413, in execute
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "omnidb-server.py", line 289, in <module>
  File "omnidb-server.py", line 255, in create_user
  File "django/contrib/auth/models.py", line 146, in create_user
  File "django/contrib/auth/models.py", line 140, in _create_user
  File "django/contrib/auth/base_user.py", line 67, in save
  File "django/db/models/base.py", line 754, in save
  File "django/db/models/base.py", line 792, in save_base
  File "django/db/models/base.py", line 895, in _save_table
  File "django/db/models/base.py", line 935, in _do_insert
  File "django/db/models/manager.py", line 85, in manager_method
  File "django/db/models/query.py", line 1254, in _insert
  File "django/db/models/sql/compiler.py", line 1397, in execute_sql
  File "django/db/backends/utils.py", line 66, in execute
  File "django/db/backends/utils.py", line 75, in _execute_with_wrappers
  File "django/db/backends/utils.py", line 84, in _execute
  File "django/db/utils.py", line 90, in __exit__
  File "django/db/backends/utils.py", line 84, in _execute
  File "django/db/backends/sqlite3/base.py", line 413, in execute
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
[2290] Failed to execute script omnidb-server
```

I know that the solution can be to do omnidb-server -r to reset the database but why would I needto do it everytime I boot?

**Comment by felipebiox** [comment]
Hi @BarryThrill ,

Resetting the database should not be a requirement at all. I will give some thought into this and get back to this issue.

Best regards
