### ISSUE TITLE
Cockroach DB connector

### ISSUE THREAD

**Issue by wodka** [OmniDB/OmniDB#1258]
Hi, 

Is there a way to limit ie the postgres functions used to a certain version? Cockroach is working mostly with your postgres connector but then fails for some queries (like having cursors: https://github.com/cockroachdb/cockroach/issues/41412?version=v20.2)

**Comment by wodka** [comment]
it is possible to change also the backend storage to cockroachdb - requiring a few changes:

add cockroach db connector
```sh
pip install django-cockroachdb~=3.1.0 # corresponding django version
```

update the config.py
```python
DATABASES = {
    'default': {
        'ENGINE': 'django_cockroachdb',
```

fix the initial migration to not create "Connection.user" as a string:
```python
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # CHANGE START
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), 
                # CHANGE END
                ('alias', models.CharField(default='', max_length=200)),
                ('conn_string', models.TextField(default='')),
                ('database', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('port', models.CharField(default='', max_length=50)),
                ('server', models.CharField(default='', max_length=200)),
                ('ssh_key', models.TextField(default='')),
                ('ssh_password', models.CharField(default='', max_length=200)),
                ('ssh_port', models.CharField(default='', max_length=50)),
                ('ssh_server', models.CharField(default='', max_length=200)),
                ('ssh_user', models.CharField(default='', max_length=200)),
                ('use_tunnel', models.BooleanField(default=False)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OmniDB_app.Technology')),
            ],
        ),
```

with those changes the migrations and settings store work with cockroach.

**Comment by wodka** [comment]
Only problem that happens is that Cockroach generated pretty high ID values per default - like `648175667981778945` - using those fails in various ways:

```
omnidb_1  | [04/08/2021 10:46:21] ERROR [django.request:224] Internal Server Error: /renew_password/
omnidb_1  | Traceback (most recent call last):
omnidb_1  |   File "/home/omnidb/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
omnidb_1  |     response = get_response(request)
omnidb_1  |   File "/home/omnidb/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
omnidb_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
omnidb_1  |   File "/opt/OmniDB/OmniDB/OmniDB_app/views/memory_objects.py", line 46, in wrap
omnidb_1  |     return function(request, *args, **kwargs)
omnidb_1  |   File "/opt/OmniDB/OmniDB/OmniDB_app/views/workspace.py", line 418, in renew_password
omnidb_1  |     v_database_object = v_session.v_databases[v_database_index]
omnidb_1  | KeyError: 648177553409409000
omnidb_1  | [04/08/2021 10:57:50] ERROR [django.request:224] Internal Server Error: /test_connection/
omnidb_1  | Traceback (most recent call last):
omnidb_1  |   File "/home/omnidb/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
omnidb_1  |     response = get_response(request)
omnidb_1  |   File "/home/omnidb/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
omnidb_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
omnidb_1  |   File "/opt/OmniDB/OmniDB/OmniDB_app/views/memory_objects.py", line 46, in wrap
omnidb_1  |     return function(request, *args, **kwargs)
omnidb_1  |   File "/opt/OmniDB/OmniDB/OmniDB_app/views/connections.py", line 240, in test_connection
omnidb_1  |     conn = Connection.objects.get(id=json_object['id'])
omnidb_1  |   File "/home/omnidb/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
omnidb_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
omnidb_1  |   File "/home/omnidb/.local/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
omnidb_1  |     raise self.model.DoesNotExist(
omnidb_1  | OmniDB_app.models.main.Connection.DoesNotExist: Connection matching query does not exist.
```

**Comment by wodka** [comment]
is there a way for a driver to disable the cursor? sadly changing v_use_server_cursor to False does not disable it (cockroach does not support cursors)

**Comment by jesusvico** [comment]
Were you able to solve the problem with the cursors? I'm having this same problem too.

**Comment by wodka** [comment]
I moved away from omnidb to adminer (it is a lot simpler - so when you are using more than just showing and editing data than this is no solution for you, it only required one simple fix: https://github.com/vrana/adminer/pull/427)

**Comment by jesusvico** [comment]
> I moved away from omnidb to adminer (it is a lot simpler - so when you are using more than just showing and editing data than this is no solution for you, it only required one simple fix: [vrana/adminer#427](https://github.com/vrana/adminer/pull/427))

I need the ldap authentication so I think that adminer is not an option for me.
