### ISSUE TITLE
Fail to start after a fresh install (Debian 11 OmniDB 3.0.3b+ds-1)

### ISSUE THREAD

**Issue by jej** [OmniDB/OmniDB#1286]
After a fresh install on a clean debian, I get this error:
```
# omnidb-server                       
Copying config file to home directory.
Traceback (most recent call last):     
  File "/usr/bin/omnidb-server", line 133, in <module>
    shutil.copyfile(os.path.join(OmniDB.custom_settings.BASE_DIR, 'config.py'), config_file)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/config.py'

```
Any idea? Thanks.

Edit: installed from the debian package

**Comment by pedroardaglio** [comment]
I'm also having the exact same problem. I'm trying to run it on Debian 11.

**Comment by eaphone** [comment]
use startup parameter -C to specified the folder path contains config.py.
