### ISSUE TITLE
mariabd mysql error 3.0.3b

### ISSUE THREAD

**Issue by lcslouis** [OmniDB/OmniDB#1305]
[12/02/2021 18:23:40] ERROR [django.request:224] Internal Server Error: /get_tree_info_mariadb/
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/OmniDB-3.0.3b/OmniDB/OmniDB_app/views/memory_objects.py", line 46, in wrap
    return function(request, *args, **kwargs)
  File "/opt/OmniDB-3.0.3b/OmniDB/OmniDB_app/views/memory_objects.py", line 96, in wrap
    return function(request, v_database, *args, **kwargs)
TypeError: get_tree_info() takes 1 positional argument but 2 were given

**Comment by arran4** [comment]
Got this as well
![image](https://user-images.githubusercontent.com/111667/158720427-a276f8e6-7817-4295-8f0c-ad8f2bf4b241.png)
Same version
