### ISSUE TITLE
Omnidb 3.0.3b crashing with SSL errors 

### ISSUE THREAD

**Issue by subliminalsmurf666** [OmniDB/OmniDB#1308]
Hi, 

I just upgraded to version 3.0.3b using the same settings with the same ssl certificate which is definitely valid, however, after a month or so of running fine, I'm now seeing the following every couple of hours or less.

I want to bring this version live on Monday but, alas, last minute it's causing me havok. 
 Please advise? A restart brings it back up but only for a small amount of time.

Jan 14 19:57:34 omnidbmax omnidb-server[27636]: Traceback (most recent call last):
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "cheroot/server.py", line 1810, in serve
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "cheroot/connections.py", line 201, in run
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "cheroot/connections.py", line 218, in _run
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "cheroot/connections.py", line 271, in _from_server_socket
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "cheroot/ssl/builtin.py", line 278, in wrap
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "ssl.py", line 423, in wrap_socket
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "ssl.py", line 870, in _create
Jan 14 19:57:34 omnidbmax omnidb-server[27636]:   File "ssl.py", line 1139, in do_handshake
Jan 14 19:57:34 omnidbmax omnidb-server[27636]: ssl.SSLError: [SSL: BAD_DH_G_LENGTH] bad key share (_ssl.c:1091)

**Comment by bradmurray** [comment]
https://omnidb.org is showing an error and has been for weeks at this point so I'm assuming it's abandoned.
