### ISSUE TITLE
Request error while expanding the PostgreSql (schema list)

### ISSUE THREAD

**Issue by kumarnitish1985** [OmniDB/OmniDB#302]
<img width="1657" alt="screen shot 2017-12-06 at 11 26 46 am" src="https://user-images.githubusercontent.com/27444632/33682475-6c066ed4-da7c-11e7-8205-207891e3748a.png">

I'm able to successfully login using my connection. also able to write query. but not able to see tables/schema left side. whenever clicking on that I'm getting attached error  like "Request error". 

any help will be really appreciated. 

Thanks
Nitish

**Comment by rafaelthca** [comment]
Hi there,

We don't support Amazon Redshift, the action of opening this node searches a lot of metadata from the database and redshift probably has different metadata. I will add an issue to investigate that.

Could you please share with us the file omnidb.log? I can see that you are using omnidb-app. This file is located in a subdirectory log in OmniDB's root folder:

Windows:

C:/omnidb-app/log/omnidb.log

Linux:

/opt/omnidb-app/log/omnidb.log

OSX:

Right click in the application icon -> Show Package Contents -> MacOS -> log -> omnidb.log

Rafael.

**Comment by kumarnitish1985** [comment]
Hi Rafael, 

Thanks for looking into it. here is the log : 

Traceback (most recent call last):
  File "/home/ec2-user/dataportal_omnidb_2017dec07/OmniDB/OmniDB_app/include/Spartacus/Database.py", line 899, in ExecuteScalar
    self.v_cur.execute(p_sql)
  File "/usr/local/lib64/python3.4/site-packages/psycopg2/extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: must be superuser to examine "server_version"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/dataportal_omnidb_2017dec07/OmniDB/OmniDB_app/views/tree_postgresql.py", line 46, in get_tree_info
    'version': v_database.GetVersion(),
  File "/home/ec2-user/dataportal_omnidb_2017dec07/OmniDB/OmniDB_app/include/OmniDatabase/__init__.py", line 155, in GetVersion
    return 'PostgreSQL ' + self.v_connection.ExecuteScalar('show server_version')
  File "/home/ec2-user/dataportal_omnidb_2017dec07/OmniDB/OmniDB_app/include/Spartacus/Database.py", line 909, in ExecuteScalar
    raise Spartacus.Database.Exception(str(exc))
OmniDB_app.include.Spartacus.Database.Exception: must be superuser to examine "server_version"

[12/11/2017 19:04:45] ERROR [django.server:124] "POST /get_tree_info_postgresql/ HTTP/1.1" 500 18076

**Comment by rafaelthca** [comment]
Thank you kumarnitish1985,

One of the information gathered when that node is opened is the server version. In redshift it looks like the db user needs to be superuser to run the command "show server_version". If you connect to the database with a superuser you won't experience this issue.

Again, we don't support redshift yet so you may encounter additional errors.

I will create an issue to add support to redshift.

Thank you for the feedback.

Rafael.

**Comment by kumarnitish1985** [comment]
Thanks Rafael. really appreciated. 

I changed the password of admin, and forgot it. how can I reset that ? 

Thanks
Nitish

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

Unfortunately OmniDB does not allow reset of password in an external way yet.

But you can create a new superuser with the `omnidb-config-server` tool, this way:

```
omnidb-config-server -c admin2 yourpasswd
```

Then you can login with new user `admin2` and change password of user `admin` by the web interface.

**Comment by kumarnitish1985** [comment]
Hi @wind39, 

I only see these files when OmniDB]$ ls  

db.sqlite3  log        nohup.out  OmniDB_app     omnidb.conf       omnidb.db        OmniDB-mac.spec   OmniDB-win.spec
deploy      manage.py  OmniDB     omnidb-app.py  omnidb-config.py  OmniDB-lin.spec  omnidb-server.py

..............
Then I ran following command : 
OmniDB]$ python3 omnidb-config.py -c admin1 adminP
it says user created successfully , but I'm not able to login into interface using new user.

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

Sorry, I just saw by the logs you sent you are using OmniDB app, not server.

How are you starting OmniDB app?

**Comment by kumarnitish1985** [comment]
Hi @wind39,
I'm running this command to start the server. I'm able to login with other normal users which were created earlier. but not with super user which I created. 
nohup python3 manage.py runserver 172.27.11.11:8002 &

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

Thanks for taking the time to dig on this. Please paste the output of

```
python3 omnidb-server.py --version
```

**Comment by kumarnitish1985** [comment]
Hi @wind39, 

I'm getting this error when ran that command. 

![screen shot 2018-01-04 at 11 07 06 am](https://user-images.githubusercontent.com/27444632/34579841-8431c1aa-f13f-11e7-8da6-3106c8538e30.png)

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

In this case:

```
python3 omnidb-config.py --version
```

**Comment by kumarnitish1985** [comment]
Hi @wind39 , 

I'm getting this output : OmniDB 2.3.0

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

Thanks. Would you please try to login with new user `admin1` again and then paste the last lines of file `log/omnidb.log`?

**Comment by kumarnitish1985** [comment]
Hi @wind39,

I don't see any log for today's date. I can see yesterday's log : 
[01/03/2018 23:31:45] INFO [OmniDB_app.views.login:184] User "alex" logged in.
[01/03/2018 23:55:28] INFO [OmniDB_app.views.login:184] User "alex" logged in.

**Comment by kumarnitish1985** [comment]
Hi @wind39, 

Thanks for your help. I found the problem, seems like my load balancer was redirecting to the different instance. thanks again.

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

Glad you found the problem.

Although we will keep this issue open as it is about support to Amazon Redshift. It may take some time because we don't have an Amazon Redshift instance to play yet. We will keep you posted :)

**Comment by wind39** [comment]
Hi @kumarnitish1985 ,

Can you please confirm server version? Is it 2.3.0?

**Comment by kumarnitish1985** [comment]
Hi @wind39,

Yes, It's 2.3.0 

#OMNIDB PARAMETERS
OMNIDB_DATABASE            = os.path.join(BASE_DIR, 'omnidb.db')
OMNIDB_VERSION             = 'OmniDB 2.3.0'
BINDKEY_EXECUTE            = 'alt+q'
BINDKEY_EXECUTE_MAC        = 'ctrl+q'
BINDKEY_REPLACE            = 'ctrl+g'
BINDKEY_REPLACE_MAC        = 'ctrl+g'
OMNIDB_DEFAULT_SERVER_PORT = 8000
OMNIDB_DEFAULT_APP_PORT    = 25480
WS_QUERY_PORT              = 25482
IS_SSL                     = False
SSL_CERTIFICATE            = ""
SSL_KEY                    = ""
CH_CMDS_PER_PAGE           = 20
PWD_TIMEOUT_TOTAL          = 1800
PWD_TIMEOUT_REFRESH        = 300
DESKTOP_MODE               = False

**Comment by wind39** [comment]
Hi, @kumarnitish1985 ,

Recently we released some improvements to deployment behind load balancers. Can you please try last version (2.6.0)? Also you may find useful this [document](https://omnidb.org/en/documentation-en/19-deploying-omnidb-server) we wrote about deployment.

Regards,
William Ivanski

**Comment by kumarnitish1985** [comment]
That’s great! I’m going to deploy latest version next week.

Also, seems like we are having problem if using it in Internet Explorer browser. Is it know issue ?

Thanks
Nitish

Sent from my iPhone

On Mar 23, 2018, at 12:47 PM, William Ivanski <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, @kumarnitish1985</kumarnitish1985> ,

Recently we released some improvements to deployment behind load balancers. Can you please try last version (2.6.0)? Also you may find useful this document<https://omnidb.org/en/documentation-en/19-deploying-omnidb-server> we wrote about deployment.

Regards,
William Ivanski
