### ISSUE TITLE
OmniDB app não abre.

### ISSUE THREAD

**Issue by Caveira1166** [OmniDB/OmniDB#320]
Tentei abrir o Omnidb App no Ubuntu 17.10 e nada acontece. Abri um terminal e digitei omndb-app e apareceu a seguinte mensagem:
```
orlei@caveira:~$ omnidb-app
Traceback (most recent call last):
  File "omnidb-app.py", line 33, in <module>
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/psycopg2/__init__.py", line 50, in <module>
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /opt/omnidb-app/libresolv-2-c4c53def.5.so: symbol __res_maybe_init, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Failed to execute script omnidb-app

```

**Comment by Caveira1166** [comment]
Eu estava tentando abrir o OmniDB App, mas era a versão 2.0.4. Baixei e instalei a versão 2.4.0 e abriu normalmente. Parabéns aos desenvolvedores da Ferramenta OmniDB.
