### ISSUE TITLE
mysql results encoding

### ISSUE THREAD

**Issue by vrestihnat** [OmniDB/OmniDB#553]
I have trouble with results from mysql 5.6 encoding: utf8_general_ci.
For example I get Ji?í instead of Jiří.
Please ask for solutions or advice how to set the connector?

**Comment by vinhduy11** [comment]
You can go to file `OmniDB/OmniDB/OmniDB_app/include/Spartacus/Database.py`
After that, go to class MySQL(Generic) and find:
`self.v_con = pymysql.connect(
                host=self.v_host,
                port=int(self.v_port),
                db=self.v_service,
                user=self.v_user,
                password=self.v_password)`
replace by
self.v_con = pymysql.connect(
                host=self.v_host,
                port=int(self.v_port),
                db=self.v_service,
                user=self.v_user,
                password=self.v_password**, charset='utf8',
                     use_unicode=True**)

Restart server to apply the change

**Comment by wind39** [comment]
Hi, @vrestihnat , thanks for reporting this.

Hi @vinhduy11 , thanks for the workaround you provided.

Allowing the user to set encoding in connection grid is a feature we already have in our roadmap. I will keep this open and will let you know once we have implemented and published this.

Regards,
William Ivanski

**Comment by adrian-enspired** [comment]
two additional suggestions: 

- connection charset should default to utf-8, imo. requiring users to configure this is bad.
- for the workaround, use `utf8mb4` (mysql's "utf8" **is not proper utf-8**).

**Comment by elysiumHL** [comment]
when I followed vinhduy11's advice，I find the omnidb-server got the error
```
Starting OmniDB websocket...
Checking port availability...
Starting websocket server at port 25482.
Starting OmniDB server...
Checking port availability...
Starting server OmniDB 2.9.0 at 0.0.0.0:8000.
User database version 2.9.0 is already matching server version.
Open OmniDB in your favorite browser
Press Ctrl+C to exit
[8] Failed to execute script omnidb-server
Traceback (most recent call last):
  File "omnidb-server.py", line 319, in <module>
  File "omnidb-server.py", line 269, in run
  File "site-packages/cherrypy/process/wspbus.py", line 369, in block
  File "site-packages/cherrypy/process/wspbus.py", line 422, in _do_execv
ValueError: execv() arg 2 must not be empty
```
by the way the os is centos7.4

**Comment by joeky888** [comment]
I think this can be closed after https://github.com/OmniDB/OmniDB/commit/944ffca667c5311f4f32b08b916e0190dac72312

```diff
- password=self.v_password)
+ password=self.v_password,
+ charset=self.v_encoding)
```

**Comment by wind39** [comment]
Hi,

Currently this ticket requires implementation of a field for encoding in the connection grid.

Regards,

William
