### ISSUE TITLE
Unable to Connect to OmniDB-Server

### ISSUE THREAD

**Issue by adrian-enspired** [OmniDB/OmniDB#600]
I've looked through the docs and issues, but I couldn't find anything addressing this problem (or any problem connecting). If it's covered somewhere please let me know.

I've starting omnidb-server successfully, but it does not load in the browser. The request eventually times out.  I've tried specifying `-H` with the correct public IP, but it fails to start:
```
root@openvpn-1:~# omnidb-server -H ***.***.***.***
Starting OmniDB websocket...
Checking port availability...
Starting websocket server at port 25482.
[07/03/2018 12:28:40] ERROR [OmniDB_app.QueryServer:480] *** Exception ***
Traceback (most recent call last):
  File "OmniDB/ws_core.py", line 476, in start_wsserver
  File "site-packages/tornado/tcpserver.py", line 142, in listen
  File "site-packages/tornado/netutil.py", line 197, in bind_sockets
OSError: [Errno 99] Cannot assign requested address

Starting OmniDB server...
Checking port availability...
Port 8000 is busy, trying another port...
Starting server OmniDB 2.9.0 at ***.***.***.***:4737.
User database version 2.9.0 is already matching server version.
[07/03/2018 12:28:40] ERROR [cherrypy.error:222] [03/Jul/2018:12:28:40] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
  File "site-packages/cheroot/server.py", line 1675, in start
OSError: No socket could be created -- (('***.***.***.***', 4737): [Errno 99] Cannot assign requested address)
```
I'm using version 2.9.0 on ubuntu 18.04

**Comment by wind39** [comment]
Hi @adrian-enspired ,

Thanks for reaching out. Does the server where OmniDB is installed have this public IP, or is the server behind a gateway/proxy?

Also, what is operating system version and OmniDB version?

Regards,
William Ivanski

**Comment by adrian-enspired** [comment]
Hi @wind39 

It's a public IP.
The OS is Ubuntu Server 18.04.  Using OmniDB server 2.9.0.

**Comment by wind39** [comment]
Hi @adrian-enspired ,

Is the public IP assigned to some of the servers' network interfaces?

**Comment by rafaelthca** [comment]
Hi @adrian-enspired, let me clarify what @wind39 asked.

You can only directly bind to an IP address that the server has been configured for. You mentioned that you tried to use a public IP address, does that address appear in the list of interfaces displayed by the command `ifconfig`?

My cloud machine has the following IP addresses assigned to it:

xxx.yyy.www.zzz
127.0.0.1

So I can start OmniDB with those IP addresses. Other applications like nginx and apache work the same way. 

If your server is behind a router or load balancer you will have to start OmniDB using a local IP address and redirect requests to it.

Rafael.

**Comment by wind39** [comment]
Hi @adrian-enspired ,

Just checking it @rafaelthca 's instructions helped you connect to the OmniDB server?

Regards,

William Ivanski

**Comment by PauloLaScience** [comment]
Hi,
When I start omnidb-server as:
`omnidb-server -p 8000 -w 25482 -H 0.0.0.0`
No problem to connect from my PC browser so I modify omnidb.conf
`listening_address = 0.0.0.0` the service don't use this config:
`[root@pgsqlmonitor-001 omnidb-server][0]# systemctl status omnidb.service
* omnidb.service - OmniDB server daemon
   Loaded: loaded (/etc/systemd/system/omnidb.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
 
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Checking port availability...
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Starting websocket server at port 25482.
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Starting OmniDB server...
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Checking port availability...
Nov 29 09:18:42 pgsqlmonitor-001.pol.be bash[26736]: Starting server OmniDB 2.12.0 at 127.0.0.1:8000.
Nov 29 09:18:43 pgsqlmonitor-001.pol.be bash[26736]: User database version 2.12.0 is already matching server version.
Nov 29 09:18:43 pgsqlmonitor-001.pol.be bash[26736]: Open OmniDB in your favorite browser
Nov 29 09:18:43 pgsqlmonitor-001.pol.be bash[26736]: Press Ctrl+C to exit
`
As you can see in the screenshot of `systemctl status omnidb.service`

Regards,
Paul-Emmanuel Devadder

**Comment by wind39** [comment]
Hi @PauloLaScience ,

Thank you very much for reaching out and reporting this.

When OmniDB server is first started as a systemd service, a folder `.omnidb/omnidb-server` is created in root home folder. Inside this folder, OmniDB creates a copy of file `omnidb.conf` as it was in `/opt/omnidb-server/omnidb.conf` when it first started. When you start `omnidb-server` without the `-c` switch, OmniDB uses the configuration file that is in the user's home folder. This is done to allow several users start its own `omnidb-server` instance.

So in your case, for now you can change `/root/.omnidb/omnidb-server/omnidb.conf` and restart OmniDB service.

For next release, I'll change the `omnidb-server` package to store its configuration files in a more Unix-like path, for example `/etc/omnidb.conf`. Then OmniDB service will use this file.

Best regards,

William

**Comment by PauloLaScience** [comment]
Hi @wind39,
It's working fine since I update `/root/.omnidb/omnidb-server/omnidb.conf`

Many thanks,
Paulo
