### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by everneret** [OmniDB/OmniDB#943]
Hello,

Since installing 2.15, many users reported slowdowns and unresponsive pages when trying to use OmniDB. We investigated and here's what we found :

```
[05/09/2019 09:23:35] ERROR [cherrypy.error:216] [09/May/2019:09:23:35] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "site-packages/cheroot/server.py", line 1753, in serve
  File "site-packages/cheroot/server.py", line 1943, in tick
  File "socket.py", line 205, in accept
OSError: [Errno 24] Too many open files

[05/09/2019 09:23:38] ERROR [django.request:228] Internal Server Error: /workspace/
Traceback (most recent call last):
  File "OmniDB_app/include/Spartacus/Database.py", line 677, in Open
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/django/core/handlers/exception.py", line 34, in inner
  File "site-packages/django/core/handlers/base.py", line 126, in _get_response
  File "site-packages/django/core/handlers/base.py", line 124, in _get_response
  File "OmniDB_app/views/workspace.py", line 66, in index
  File "OmniDB_app/include/Spartacus/Database.py", line 708, in Query
  File "OmniDB_app/include/Spartacus/Database.py", line 693, in Query
  File "OmniDB_app/include/Spartacus/Database.py", line 686, in Open
OmniDB_app.include.Spartacus.Database.Exception: unable to open database file
```

I guess it's kinda related to 2.15 since we had no such issue with 2.14. Will do further investigation. Or could it be related to the fact that I created 30+ OmniDB users with each 15 connections ? :thinking: 

Thanks for reading,

Ed.

**Comment by rafaelthca** [comment]
Hi @everneret,

thanks for reporting. This is critical, I'm starting investigation now, will get back to you.

Rafael.

**Comment by rafaelthca** [comment]
Hi again,

What action did you take? Did you restart OmniDB? Can you please monitor the number
of opened files of your omnidb process?

![Screen Shot 2019-05-09 at 7 46 53 AM](https://user-images.githubusercontent.com/9335851/57447970-b0b19180-722e-11e9-9aaa-c4c44ff9af12.png)

We are interested in the process with more CPU time (the second). Once you find it, use the following command, changing the final pid.

![Screen Shot 2019-05-09 at 7 48 50 AM](https://user-images.githubusercontent.com/9335851/57448076-e9516b00-722e-11e9-8ad5-924c48f3001f.png)

If you can please monitor that number of opened files. We want to make sure there isn't some sort of leak there.

2.15 introduced the SSH terminal feature. Do you know if any of your users is using it?

Will continue investigation.

**Comment by rafaelthca** [comment]
I think I found the culprit, OmniDB is keeping opened file handlers when accessing
the local database file (in a specific operation). I'll confirm this once again ad fix it.

Once fixed, would you like a custom build for your environment with the fix?

Rafael.

**Comment by everneret** [comment]
Hi Rafael,

As far as I know, no one here is using the SSH terminal feature.
We already rolled back to 2.14 so I won't be able to answer your question right away. Let me check.

When I encountered the problem, I noticed high CPU usage while only trying to load the page (not logged in I think).

We restarted OmniDB and it got back to normal.

Thanks,

Ed.

**Comment by everneret** [comment]
Rafael,

Great news!

A custom fixed build would in fact be amazing :)

Thanks,

Ed.

**Comment by rafaelthca** [comment]
@everneret,

What omnidb installation package do you use?

**Comment by everneret** [comment]
We used the .deb package

**Comment by rafaelthca** [comment]
@everneret,

Here is the link with the patched version:

https://omnidb.org/dist/2.15.0_fix/omnidb-server_2.15.0-debian-amd64.deb

The bug was in the websocket server, related to a new feature in 2.15.0.

We will be officially releasing this fix in the upcoming weeks.

Thanks for reporting.

**Comment by everneret** [comment]
Hi Rafael,

I'll get this installed and give you some feedback ASAP.

Thanks,

Ed.

**Comment by everneret** [comment]
Hi, 

We've been using the 2.15.0_fix version since May 10th. Everything works fine almost all the time, but we encountered the problem again (only once though) :

```
[05/20/2019 15:22:04] ERROR [cherrypy.error:216] [20/May/2019:15:22:04] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "site-packages/cheroot/server.py", line 1789, in serve
  File "site-packages/cheroot/server.py", line 1982, in tick
  File "socket.py", line 205, in accept
OSError: [Errno 24] Too many open files
```

Thanks,

Ed.

**Comment by rafaelthca** [comment]
That's not good. Did you restart again? Can you please perform the same tests I did in this comment:

https://github.com/OmniDB/OmniDB/issues/943#issuecomment-490854868

If you could monitor the number of opened files on a regular basis, maybe we can identify another leak. That would give you a special spot in our testers hall of fame :)

It may not be a leak, though. Depending on the load and how your server is configured, OmniDB may be reaching a limit in file descriptors per process, which can be increased.

Rafael.

**Comment by everneret** [comment]
Hi,

OmniDB was indeed restarted.

I'll monitor the open files and tell you what. 

Currently it justs works smoothly :) 

Ed.

**Comment by everneret** [comment]
Hello,

We experienced a new outage and we could monitor the open files, please find the attached results.

As a scale reminder, we're 20+ users browsing 10+ servers.

Hope this helps ;)

Ed.

[omnidb_analysis.txt](https://github.com/OmniDB/OmniDB/files/3296246/omnidb_analysis.txt)

**Comment by rafaelthca** [comment]
Thank you very much. Very helpful.

There are 1102 file descriptors tied to OmniDB. The first thing to mention here
is that the limit of FDs can be increased. Debian limits the number of FDs per
process to 1024, by default. That can be increased and several applications require
that, as they use a lot of FDs.

That said, I believe OmniDB is having some issues in your setup. From the 1102 FDs,
928 are of the following type:

```
omnidb-se 29690 omnidb 1021u     IPv4           37080269      0t0      TCP xx.xx.xx.xx:25482->xx.xx.xx.xx:40644 (ESTABLISHED)
```

Which is a client connected to the websocket server. I doubt that you have 928
clients currently connected to OmniDB :)

The issue seems to be that OmniDB is not detecting client disconnections and is
keeping file descriptors of each client (which is probably not active anymore)
in the websocket server.

The websocket server doesn't know that a client disconnected unless you explicitly
close OmniDB's interface in the browser.

I added a fix for that in 2.16, which was released last week. Now the server keeps
track of each client and disconnects them if they are inactive. I believe this should
fix your issue.

Can you tell me if the outage happened with 2.15? Or did you experience after upgrading
to 2.16 too?

**Comment by everneret** [comment]
Hi,

It happened with the 2.15.0_fix version. People tend to always keep an open browser tab on OmniDB, with multiple inner and outer tabs in the app.

We plan to install 2.16 this week, so hopefully this will be history ;)

Ed.
