### ISSUE TITLE
OmniDB server installation problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by cschwaderer** [OmniDB/OmniDB#993]
I have both OmniDB app and server 2.15 installed in Ubuntu 18.04. That used to work quite well until recently.

Running `apt upgrade` told me

> The following NEW packages will be installed:
  fonts-glewlwyd fonts-roboto-unhinted libjs-excanvas libjs-jquery-ui omnidb-common python-django-common python3-attr python3-bs4 python3-cherrypy3 python3-click python3-colorama python3-django python3-et-xmlfile python3-html5lib python3-jdcal python3-lxml
  python3-openpyxl python3-paramiko python3-pgspecial python3-pluggy python3-prettytable python3-psycopg2 python3-py python3-pyaes python3-pyasn1 python3-pytest python3-repoze.lru python3-restrictedpython python3-routes python3-scrypt python3-simplejson
  python3-sqlparse python3-sshtunnel python3-tornado python3-tz python3-webencodings python3-webob
The following packages will be upgraded:
  omnidb-server

I didn't pay much attention, however, actually running the upgrade resulted in

> The following packages have unmet dependencies:
 omnidb-server : Depends: omnidb-common (= 2.15.0+ds-1.pgdg18.04+1) but it is not installed

At this point, running `omnidb-server` from the command line resulted in

> bash: /usr/bin/omnidb-server: No such file or directory

After running `apt --fix-broken install` I got when trying `omnidb-server as root

> Traceback (most recent call last):
  File "/usr/bin/omnidb-server", line 176, in <module>
    import OmniDB_app.urls
  File "/usr/lib/python3/dist-packages/OmniDB_app/urls.py", line 4, in <module>
    from . import views
  File "/usr/lib/python3/dist-packages/OmniDB_app/views/__init__.py", line 1, in <module>
    from . import login, connections, users, workspace, tree, tree_snippets, tree_postgresql, tree_oracle, tree_mysql, tree_mariadb, monitoring, monitor_dashboard, plugins
  File "/usr/lib/python3/dist-packages/OmniDB_app/views/login.py", line 6, in <module>
    from OmniDB import ws_core
  File "/usr/lib/python3/dist-packages/OmniDB/ws_core.py", line 619, in <module>
    from tornado.platform.asyncio import AnyThreadEventLoopPolicy
ImportError: cannot import name 'AnyThreadEventLoopPolicy'

While for a non-root user (which worked before) I got

> Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/lib/omnidb/omnidb.log'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/omnidb-server", line 163, in <module>
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'logfile_django': [Errno 13] Permission denied: '/var/lib/omnidb/omnidb.log'

What did help was 

- `apt purge omnidb-server*`

- `apt autoremove`

- Re-install omnidb-server

However, now I am at the same state as before: apt wants to updated omnidb-server

**Comment by wind39** [comment]
Hi @cschwaderer ,

Thanks for reaching out. Currently the [README](https://github.com/OmniDB/OmniDB#111--debian--ubuntu-repository) explains how to install OmniDB app, server and the debugger plugin for PostgreSQL from my Debian repository in BinTray:

```
apt install apt-transport-https dirmngr
echo "deb https://dl.bintray.com/wind39/omnidb-deb debian main" > /etc/apt/sources.list.d/omnidb.list
apt-key adv --recv-keys 379CE192D401AB61
apt update

apt install omnidb-app        # for the app; or
apt install omnidb-server     # for the server; or
apt install omnidb-plugin     # for the plugin
```

However, recently the Debian PGDG Team kindly included OmniDB server and debugger plugin packages in [Debian PGDG repository](https://ftp-master.debian.org/new/omnidb_2.15.0+ds-1.html).

So `apt` is trying to install OmniDB from Debian PGDG repo, which can only be executed as root and is conflicting with your current `omnidb-server` package.

So for now you have 2 options:

1) Install OmniDB server from PGDG: Amend file `/etc/apt/sources.list.d/omnidb.list` and comment out the line `deb https://dl.bintray.com/wind39/omnidb-deb debian main`, then run `apt update && apt upgrade` (please note that we are still in transition phase, testing packages from PGDG, and will send detailed instructions soon); or

2) For now, pin `omnidb-server` to version 2.15.0 to avoid `apt upgrade` to try to upgrade it. We are releasing 2.16.0 in a few days. Please wait for instructions.

Regards,

William

**Comment by wind39** [comment]
Hi @cschwaderer ,

Today we released OmniDB 2.16.0. Please upgrade the OmniDB packages to 2.16.0 from our repository in BinTray, as instructed in the README.

As for the issues with the `omnidb-server` package from PGDG, I reported them here:

https://salsa.debian.org/postgresql/omnidb/issues/1

Best regards,

William

**Comment by Nextafari** [comment]
You could also switch to the root user, that was what worked for me. typing  `su` in bash and entering your root user's password
